# Generated by Django 5.0.7 on 2024-07-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mc_donalds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='full_name',
        ),
    ]
